name: salespulse
description: SalesPulse - Track your sales and expenses with ease. Manage your business on the go.
publish_to: 'none'
version: 1.0.4+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  http: ^1.3.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.3
  path_provider: ^2.1.4
  open_file: ^3.5.7
  url_launcher: ^6.3.1
  dio: ^5.7.0
  package_info_plus: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Optimize assets - only include necessary files
  # assets:
  #   - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/AppIcons/playstore.png"
  image_path_android: "assets/AppIcons/playstore.png"
  image_path_ios: "assets/AppIcons/appstore.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/AppIcons/playstore.png"
